-- Seed do cadastro mestre de colaboradores (roster usado no PWA).
-- A tabela employees so era populada de forma preguicosa via ensure_employee()
-- quando alguem de fato logava e enviava um checklist, entao dropdowns como
-- o seletor de colaborador em Configuracao de Metas so mostravam quem ja tinha
-- usado o app. Este seed sincroniza o roster completo (120 pessoas).

insert into public.employees (matricula, nome, nome_completo, gerencia, base, funcao)
values
  ('23847', 'Afonso', 'Afonso Lucas Campos Alcantara', 'GSTC', 'BCB', 'Coordenador'),
  ('462', 'Antonio R.', 'Antonio Marcos Salazar dos Reis', 'GERE', 'BCB', 'Supervisor'),
  ('12512', 'Deilton', 'Deilton Souza Ribeiro', 'GSTC', 'BCB', 'Supervisor'),
  ('12558', 'Diego A.', 'Diego Santos Alencar', 'GERE', 'BCB', 'Fiscal'),
  ('12471', 'Dyulijan', 'Dyulijan Pereira de Oliveira', 'GOMAN', 'BCB', 'Encarregado'),
  ('13516', 'Elismar', 'Elismar Rocha de Sousa', 'GOMAN', 'BCB', 'Encarregado'),
  ('13315', 'Everaldo', 'Everaldo Nogueira Filho', 'GOMAN', 'BCB', 'Supervisor'),
  ('12582', 'Francisco Ada.', 'Francisco Adalton de Oliveira Lima', 'GSTC', 'BCB', 'Fiscal'),
  ('12509', 'Francisco Cha.', 'Francisco das Chagas Pereira Lima', 'GOMAN', 'BCB', 'Encarregado'),
  ('12570', 'Francisco G.', 'Francisco Flavio Reis Gomes', 'GOMAN', 'BCB', 'Encarregado'),
  ('23742', 'Francisco S.', 'Francisco Leandro Nunes da Silva', 'SESMT', 'BCB', 'Tec. Seguranca'),
  ('12576', 'Gleyson', 'Gleyson de Sousa Silva', 'GSTC', 'BCB', 'Fiscal'),
  ('13947', 'Isaac', 'Isaac da Cunha Alves Silva', 'GERE', 'BCB', 'Fiscal'),
  ('12690', 'Italo B.', 'Italo Bruno da Silva Fontes', 'GOMAN', 'BCB', 'Analista de Desempenho'),
  ('15565', 'Jackson', 'Jackson Kentelly Marculino de Souza', 'ADM', 'BCB', 'Administrativo'),
  ('22025', 'Julio', 'Julio Cesar de Souza Sangi', 'GERE', 'BCB', 'Coordenador'),
  ('12595', 'Lucas A.', 'Lucas Alves de Almeida', 'GSTC', 'BCB', 'Fiscal'),
  ('16153', 'Lucas S.', 'Lucas Moreira de Souza', 'OFICINA', 'BCB', 'Coordenador'),
  ('12746', 'Luis A.', 'Luis Filipe Cantanhede Alves', 'GERE', 'BCB', 'Supervisor'),
  ('12597', 'Manoel P.', 'Manoel da Silva Protasio', 'GOMAN', 'BCB', 'Encarregado'),
  ('13080', 'Mikeias', 'Mikeias Veloso Pinheiro', 'GOMAN', 'BCB', 'Supervisor'),
  ('12672', 'Moises', 'Moises Ferreira de Sousa', 'GOMAN', 'BCB', 'Encarregado'),
  ('21574', 'Normam', 'Normam Matheus Barros de Oliveira', 'SESMT', 'BCB', 'Tec. Seguranca'),
  ('12517', 'Ofelio', 'Ofelio de Sousa Alves', 'GOMAN', 'BCB', 'Encarregado'),
  ('12516', 'Pablo', 'Pablo Silva Loura', 'GOMAN', 'BCB', 'Supervisor'),
  ('12354', 'Pryscilla', 'Pryscilla Cristyane Oliveira de Faria', 'ADM', 'BCB', 'Supervisor'),
  ('13744', 'Raimundo Rib.', 'Raimundo Ribeiro da Silva Filho', 'GOMAN', 'BCB', 'Encarregado'),
  ('12483', 'Renato M.', 'Renato Silva de Matos', 'GOMAN', 'BCB', 'Encarregado'),
  ('15559', 'Ricardo', 'Ricardo Malta da Cunha', 'GOMAN', 'BCB', 'Coordenador'),
  ('14475', 'Ruan', 'Ruan Valmir de Souza Silva', 'OFICINA', 'BCB', 'Supervisor'),
  ('12513', 'Wanderson', 'Wanderson Ribeiro Vale', 'GOMAN', 'BCB', 'Encarregado'),
  ('12506', 'Werbeth', 'Werbeth Rodrigues Carvalho', 'GOMAN', 'BCB', 'Supervisor'),
  ('12383', 'Weyderson', 'Weyderson Juan da Costa Santos', 'ADM', 'BCB', 'Administrativo'),
  ('13023', 'Bruno', 'Bruno Oliveira da Silva', 'GSTC', 'BDC', 'Fiscal'),
  ('18311', 'Cleomar', 'Cleomar Vieira da Silva', 'GOMAN', 'BDC', 'Encarregado'),
  ('13750', 'Geraldo', 'Geraldo Moreira Rodrigues', 'GOMAN', 'BDC', 'Encarregado'),
  ('17753', 'Idialdo', 'Idialdo dos Santos Coimbra', 'GOMAN', 'BDC', 'Supervisor'),
  ('12572', 'Jarbem', 'Jarbem Rosa Sousa', 'GOMAN', 'BDC', 'Encarregado'),
  ('17462', 'Joao A.', 'Joao Lucas Rodrigues Apoliano', 'GOMAN', 'BDC', 'Encarregado'),
  ('13518', 'Jose B.', 'Jose Francisco Rodrigues Batista', 'GOMAN', 'BDC', 'Encarregado'),
  ('12851', 'Josiel', 'Josiel Meneses dos Santos', 'GOMAN', 'BDC', 'Encarregado'),
  ('12938', 'Lucas C.', 'Lucas Oliveira Costa', 'GOMAN', 'BDC', 'Encarregado'),
  ('15455', 'Marcos', 'Marcos Felipe de Andrade Silva', 'GOMAN', 'BDC', 'Coordenador'),
  ('21614', 'Nilo', 'Nilo Goncalves da Silva Filho', 'SESMT', 'BDC', 'Tec. Seguranca'),
  ('12762', 'Cristophe', 'Cristophe Daniel dos Santos Melo', 'GOMAN', 'ITM', 'Supervisor'),
  ('13746', 'Ednaldo', 'Ednaldo da Silva Lima', 'GOMAN', 'ITM', 'Encarregado'),
  ('12751', 'Gilson', 'Gilson Ricardo Silva Cunha', 'GOMAN', 'ITM', 'Encarregado'),
  ('4745', 'Hittalo', 'Hittalo Moraes da Silva', 'GOMAN', 'ITM', 'Encarregado'),
  ('12792', 'Ivanilson', 'Ivanilson Ricardo Oliveira Santos', 'GOMAN', 'ITM', 'Encarregado'),
  ('12749', 'Joao C.', 'Joao Batista da Silva Chagas', 'GOMAN', 'ITM', 'Encarregado'),
  ('12686', 'Jose Rai.', 'Jose Raimundo Costa Filho', 'GOMAN', 'ITM', 'Encarregado'),
  ('12800', 'Leonardo A.', 'Leonardo Estrela Anchieta', 'GSTC', 'ITM', 'Supervisor'),
  ('12724', 'Raimundo M.', 'Raimundo Nonato Sousa Matos', 'GSTC', 'ITM', 'Fiscal'),
  ('12745', 'Washington', 'Washington Soares de Souza', 'GSTC', 'ITM', 'Fiscal'),
  ('21925', 'Welrisson', 'Welrisson Oliveira Sousa', 'SESMT', 'ITM', 'Tec. Seguranca'),
  ('12884', 'Beneth', 'Beneth Erikson Santos Cavalcante', 'GOMAN', 'PDS', 'Encarregado'),
  ('14983', 'Candido', 'Candido Gabriel de Melo Silva Soares', 'GOMAN', 'PDS', 'Tec. Planejamento'),
  ('12813', 'Everton', 'Everton Siqueira Pereira', 'SESMT', 'PDS', 'Supervisor'),
  ('13748', 'Fernando', 'Fernando Melo da Costa', 'GOMAN', 'PDS', 'Encarregado'),
  ('12822', 'Janes', 'Janes da Costa Melo', 'GOMAN', 'PDS', 'Encarregado'),
  ('13035', 'Joao J.', 'Joao Climaco Medeiros de Azevedo Junior', 'GOMAN', 'PDS', 'Supervisor'),
  ('12820', 'Jose Air.', 'Jose Airton do Carmo Melo Filho', 'GOMAN', 'PDS', 'Encarregado'),
  ('16331', 'Josielington', 'Josielington Paz de Oliveira', 'SESMT', 'PDS', 'Tec. Seguranca'),
  ('12848', 'Manuel', 'Manuel Silva Junior', 'GOMAN', 'PDS', 'Fiscal'),
  ('12818', 'Messias', 'Messias Abreu dos Santos', 'GOMAN', 'PDS', 'Supervisor'),
  ('12852', 'Patrick', 'Patrick Amaro Ferreira', 'GOMAN', 'PDS', 'Encarregado'),
  ('12847', 'Paulo Sil.', 'Paulo Silva Ferreira', 'GSTC', 'PDS', 'Fiscal'),
  ('12842', 'Raimundo S.', 'Raimundo Hermesson Brito Vieira da Silva', 'GSTC', 'PDS', 'Supervisor'),
  ('12882', 'Raimundo Non.', 'Raimundo Nonato da Costa Filho', 'GOMAN', 'PDS', 'Encarregado'),
  ('12844', 'Reinaldo', 'Reinaldo Santana de Lima', 'GSTC', 'PDS', 'Fiscal'),
  ('16138', 'Thomas', 'Thomas Lucas da Silva Lima', 'GERE', 'PDS', 'Fiscal'),
  ('12849', 'Valdei', 'Valdei Oliveira Silva', 'GOMAN', 'PDS', 'Encarregado'),
  ('17751', 'Vanilson', 'Vanilson Siqueira Furtado', 'GSTC', 'PDS', 'Fiscal'),
  ('20868', 'Alex', 'Alex Machado da Silva', 'GOMAN', 'PDT', 'Encarregado'),
  ('21141', 'Andre', 'Andre Silva de Sousa', 'GOMAN', 'PDT', 'Encarregado'),
  ('12889', 'Antonio Mar.', 'Antonio Marcos Santos Alencar', 'GOMAN', 'PDT', 'Supervisor'),
  ('12489', 'Antonio V.', 'Antonio Samuel Silva Viana', 'GSTC', 'PDT', 'Fiscal'),
  ('12891', 'Antonio Sil.', 'Antonio Silva de Abreu', 'SESMT', 'PDT', 'Supervisor'),
  ('13009', 'Ariosvaldo', 'Ariosvaldo Alves Soares', 'GOMAN', 'PDT', 'Encarregado'),
  ('12913', 'Augusto', 'Augusto Cesar da Silva', 'GOMAN', 'PDT', 'Encarregado'),
  ('19837', 'Camila', 'Camila Correa Araujo', 'ADM', 'PDT', 'Coordenador'),
  ('12898', 'Carlos F.', 'Carlos Sandro da Silva Florencio', 'GOMAN', 'PDT', 'Encarregado'),
  ('17747', 'Daciel', 'Daciel Pereira Ramos', 'GOMAN', 'PDT', 'Encarregado'),
  ('21607', 'Dario', 'Dario Franca Fernandes de Sousa', 'SESMT', 'PDT', 'Tec. Seguranca'),
  ('24046', 'Davi', 'Davi Cabral Santos', 'GOMAN', 'PDT', 'Encarregado'),
  ('24088', 'Edivaldo', 'Edivaldo Silva do Nascimento', 'GSTC', 'PDT', 'Fiscal'),
  ('13818', 'Edson', 'Edson de Souza Pereira', 'GERE', 'PDT', 'Fiscal'),
  ('12892', 'Francisco R.', 'Francisco de Assis Araujo Rodrigues', 'GOMAN', 'PDT', 'Encarregado'),
  ('12939', 'Gabriel', 'Gabriel do Carmo Costa', 'GOMAN', 'PDT', 'Encarregado'),
  ('12998', 'Guilherme', 'Guilherme Fonseca de Sousa Nogueira', 'GSTC', 'PDT', 'Fiscal'),
  ('12955', 'Maicon', 'Maicon Douglas Silva Alves', 'GOMAN', 'PDT', 'Encarregado'),
  ('17463', 'Marcirio', 'Marcirio Cesar Viana da Silva Neto', 'GOMAN', 'PDT', 'Encarregado'),
  ('12981', 'Marcus', 'Marcus Vinicius Soares Lima', 'GOMAN', 'PDT', 'Encarregado'),
  ('24109', 'Rafael', 'Rafael Pereira da Silva', 'GOMAN', 'PDT', 'Encarregado'),
  ('22546', 'Rafaela', 'Rafaela Melo Candido da Silva', 'GOMAN', 'PDT', 'Coordenador'),
  ('12719', 'Raimundo N.', 'Raimundo Nonato Almeida do Nascimento', 'GOMAN', 'PDT', 'Supervisor'),
  ('13021', 'Raurison', 'Raurison Cardim Oliveira', 'GOMAN', 'PDT', 'Encarregado'),
  ('16939', 'Silman', 'Silman Mario Santos Lima', 'GOMAN', 'PDT', 'Encarregado'),
  ('12928', 'Vilson', 'Vilson Alves Ferreira', 'GOMAN', 'PDT', 'Encarregado'),
  ('23605', 'Waldir', 'Waldir Carlos da Silva Junior', 'ADM', 'PDT', 'Gerente'),
  ('22511', 'Wemeson', 'Wemeson da Silva Oliveira', 'GSTC', 'PDT', 'Fiscal'),
  ('13032', 'Arlison', 'Arlison Rogerio Martins Lima', 'GSTC', 'STI', 'Supervisor'),
  ('24036', 'Carlos O.', 'Carlos Rodrigues Oliveira', 'GOMAN', 'STI', 'Encarregado'),
  ('12650', 'Diego L.', 'Diego Sousa de Lima', 'GOMAN', 'STI', 'Encarregado'),
  ('14587', 'Edivan', 'Edivan de Lima Carvalho', 'GOMAN', 'STI', 'Supervisor'),
  ('23741', 'Francisco F.', 'Francisco Junior Lima Fontenele', 'GOMAN', 'STI', 'Encarregado'),
  ('17084', 'Hugo', 'Hugo Leonardo Vieira da Silveira', 'GERE', 'STI', 'Fiscal'),
  ('13410', 'Joel', 'Joel Pereira de Araujo Filho', 'GOMAN', 'STI', 'Encarregado'),
  ('20270', 'Joise', 'Joise Kaciele Pereira Marques', 'SESMT', 'STI', 'Tec. Seguranca'),
  ('13073', 'Jorden', 'Jorden Cleyson de Lucena Mota', 'GSTC', 'STI', 'Fiscal'),
  ('13754', 'Jose M.', 'Jose Pedro Goncalves Moura', 'GOMAN', 'STI', 'Encarregado'),
  ('12742', 'Joselmo', 'Joselmo Gomes dos Santos', 'GOMAN', 'STI', 'Encarregado'),
  ('13100', 'Leonardo L.', 'Leonardo Martins de Lima', 'GOMAN', 'STI', 'Encarregado'),
  ('12515', 'Luis S.', 'Luis Carlos de Souza', 'GOMAN', 'STI', 'Supervisor'),
  ('13077', 'Madson', 'Madson Felix da Silva', 'GSTC', 'STI', 'Fiscal'),
  ('120', 'Manoel R.', 'Manoel do Nascimento Pereira Rodrigues', 'GOMAN', 'STI', 'Encarregado'),
  ('13099', 'Mateus', 'Mateus Antonio Viegas Lima', 'GOMAN', 'STI', 'Encarregado'),
  ('12467', 'Paulo Ces.', 'Paulo Cesar Rodrigues Ferreira', 'GOMAN', 'STI', 'Encarregado'),
  ('12479', 'Renato C.', 'Renato Ramos Carvalho', 'GSTC', 'STI', 'Fiscal'),
  ('13060', 'Rosiel', 'Rosiel Ferreira dos Santos', 'GOMAN', 'STI', 'Encarregado')
on conflict (matricula) do update set
  nome = excluded.nome,
  nome_completo = excluded.nome_completo,
  gerencia = excluded.gerencia,
  base = excluded.base,
  funcao = excluded.funcao,
  ativo = true,
  updated_at = now();
