-- Hierarquia dos observadores (planilha 'Equipes - OP e ADM'): coordenador, gerente e processo.
ALTER TABLE public.employees
  ADD COLUMN IF NOT EXISTS coordenador text,
  ADD COLUMN IF NOT EXISTS gerente text,
  ADD COLUMN IF NOT EXISTS processo text;

UPDATE public.employees SET coordenador='Paulo', gerente='Cesar', processo='Plantão' WHERE matricula='22899';
UPDATE public.employees SET coordenador='Julio C.', gerente='Jamerson', processo='Inspeção' WHERE matricula='12889';
UPDATE public.employees SET coordenador='Daniel', gerente='Cesar', processo='Segurança' WHERE matricula='12891';
UPDATE public.employees SET coordenador='Paulo', gerente='Cesar', processo='Plantão' WHERE matricula='12489';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='13795';
UPDATE public.employees SET coordenador='Afonso', gerente='Jamerson', processo='Plantão' WHERE matricula='12582';
UPDATE public.employees SET coordenador='Afonso', gerente='Jamerson', processo='Plantão' WHERE matricula='23847';
UPDATE public.employees SET coordenador='Thiago F.', gerente='Cesar', processo='Poda' WHERE matricula='20868';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Linha Viva' WHERE matricula='21141';
UPDATE public.employees SET coordenador='Jackson', gerente='Cesar', processo='Construção' WHERE matricula='20548';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Construção' WHERE matricula='13009';
UPDATE public.employees SET coordenador='Afonso', gerente='Jamerson', processo='Plantão' WHERE matricula='15613';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Construção' WHERE matricula='12913';
UPDATE public.employees SET coordenador='Thiago F.', gerente='Cesar', processo='Construção' WHERE matricula='12884';
UPDATE public.employees SET coordenador='Paulo', gerente='Cesar', processo='Plantão' WHERE matricula='13023';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Construção' WHERE matricula='12898';
UPDATE public.employees SET coordenador='Camila', gerente='Cesar', processo='Almoxarifado' WHERE matricula='19837';
UPDATE public.employees SET coordenador='Thiago F.', gerente='Cesar', processo='Construção' WHERE matricula='14983';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='24036';
UPDATE public.employees SET coordenador='Jackson', gerente='Cesar', processo='Construção' WHERE matricula='18311';
UPDATE public.employees SET coordenador='Thiago F.', gerente='Cesar', processo='Poda' WHERE matricula='13035';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Linha Viva' WHERE matricula='12762';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Construção' WHERE matricula='17747';
UPDATE public.employees SET coordenador='Daniel', gerente='Cesar', processo='Segurança' WHERE matricula='21607';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Construção' WHERE matricula='24046';
UPDATE public.employees SET coordenador='Afonso', gerente='Jamerson', processo='Plantão' WHERE matricula='12512';
UPDATE public.employees SET coordenador='Julio C.', gerente='Jamerson', processo='Inspeção' WHERE matricula='12558';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='12650';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Poda' WHERE matricula='12471';
UPDATE public.employees SET coordenador='Paulo', gerente='Cesar', processo='Plantão' WHERE matricula='24088';
UPDATE public.employees SET coordenador='Julio C.', gerente='Cesar', processo='Inspeção' WHERE matricula='13818';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='14587';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='13516';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Linha Viva' WHERE matricula='13315';
UPDATE public.employees SET coordenador='Daniel', gerente='Cesar', processo='Segurança' WHERE matricula='12813';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='12509';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Construção' WHERE matricula='12892';
UPDATE public.employees SET coordenador='Thiago F.', gerente='Cesar', processo='Linha Viva' WHERE matricula='13748';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='12534';
UPDATE public.employees SET coordenador='Jackson', gerente='Cesar', processo='Construção' WHERE matricula='16938';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Poda' WHERE matricula='12570';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Poda' WHERE matricula='23741';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Construção' WHERE matricula='12939';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='12751';
UPDATE public.employees SET coordenador='Afonso', gerente='Jamerson', processo='Plantão' WHERE matricula='12576';
UPDATE public.employees SET coordenador='Paulo', gerente='Cesar', processo='Plantão' WHERE matricula='12998';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='4745';
UPDATE public.employees SET coordenador='Julio C.', gerente='Jamerson', processo='Inspeção' WHERE matricula='17084';
UPDATE public.employees SET coordenador='Jackson', gerente='Cesar', processo='Construção' WHERE matricula='17753';
UPDATE public.employees SET coordenador='Julio C.', gerente='Jamerson', processo='Inspeção' WHERE matricula='13947';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Poda' WHERE matricula='12792';
UPDATE public.employees SET coordenador='Thiago F.', gerente='Cesar', processo='Construção' WHERE matricula='12820';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='23972';
UPDATE public.employees SET coordenador='Daniel', gerente='Jamerson', processo='Segurança' WHERE matricula='24793';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Poda' WHERE matricula='13754';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='12686';
UPDATE public.employees SET coordenador='Jackson', gerente='Cesar', processo='Construção' WHERE matricula='15565';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='12621';
UPDATE public.employees SET coordenador='Thiago F.', gerente='Cesar', processo='Construção' WHERE matricula='12822';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Linha Viva' WHERE matricula='12572';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='12749';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='17462';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='13410';
UPDATE public.employees SET coordenador='Afonso', gerente='Jamerson', processo='Ligação Nova' WHERE matricula='13073';
UPDATE public.employees SET coordenador='Jackson', gerente='Cesar', processo='Construção' WHERE matricula='13518';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='12742';
UPDATE public.employees SET coordenador='Jackson', gerente='Cesar', processo='Construção' WHERE matricula='12851';
UPDATE public.employees SET coordenador='Daniel', gerente='Cesar', processo='Segurança' WHERE matricula='16331';
UPDATE public.employees SET coordenador='Julio C.', gerente='Jamerson', processo='Inspeção' WHERE matricula='22025';
UPDATE public.employees SET coordenador='Julio C.', gerente='Jamerson', processo='Inspeção' WHERE matricula='12746';
UPDATE public.employees SET coordenador='Afonso', gerente='Jamerson', processo='Plantão' WHERE matricula='12800';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='13100';
UPDATE public.employees SET coordenador='Afonso', gerente='Jamerson', processo='Plantão' WHERE matricula='12595';
UPDATE public.employees SET coordenador='Ruan', gerente='Jamerson', processo='Oficina' WHERE matricula='16153';
UPDATE public.employees SET coordenador='Jackson', gerente='Cesar', processo='Construção' WHERE matricula='12938';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='12515';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Poda' WHERE matricula='12597';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='13099';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='13077';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Construção' WHERE matricula='12955';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='120';
UPDATE public.employees SET coordenador='Thiago F.', gerente='Cesar', processo='Construção' WHERE matricula='12848';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Linha Viva' WHERE matricula='17463';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='15455';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Construção' WHERE matricula='12981';
UPDATE public.employees SET coordenador='Jackson', gerente='Cesar', processo='Construção' WHERE matricula='16079';
UPDATE public.employees SET coordenador='Thiago F.', gerente='Cesar', processo='Construção' WHERE matricula='12818';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='13080';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='12672';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='17746';
UPDATE public.employees SET coordenador='Daniel', gerente='Cesar', processo='Segurança' WHERE matricula='21614';
UPDATE public.employees SET coordenador='Daniel', gerente='Jamerson', processo='Segurança' WHERE matricula='21574';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='12517';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='12467';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Equipamentos' WHERE matricula='12516';
UPDATE public.employees SET coordenador='Thiago F.', gerente='Cesar', processo='Construção' WHERE matricula='12852';
UPDATE public.employees SET coordenador='Paulo', gerente='Cesar', processo='Plantão' WHERE matricula='12847';
UPDATE public.employees SET coordenador='Valvick', gerente='Jamerson', processo='Administrativo' WHERE matricula='12354';
UPDATE public.employees SET coordenador='Paulo', gerente='Cesar', processo='Plantão' WHERE matricula='12842';
UPDATE public.employees SET coordenador='Afonso', gerente='Jamerson', processo='Plantão' WHERE matricula='12724';
UPDATE public.employees SET coordenador='Thiago F.', gerente='Cesar', processo='tat' WHERE matricula='12882';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='13744';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Construção' WHERE matricula='24109';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Linha Viva' WHERE matricula='19677';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Construção' WHERE matricula='12719';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Poda' WHERE matricula='13021';
UPDATE public.employees SET coordenador='Paulo', gerente='Cesar', processo='Plantão' WHERE matricula='12844';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='12483';
UPDATE public.employees SET coordenador='Afonso', gerente='Jamerson', processo='Plantão' WHERE matricula='12479';
UPDATE public.employees SET coordenador='Jackson', gerente='Cesar', processo='Construção' WHERE matricula='22518';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='13060';
UPDATE public.employees SET coordenador='Ruan', gerente='Jamerson', processo='Oficina' WHERE matricula='14475';
UPDATE public.employees SET coordenador='Julio C.', gerente='Jamerson', processo='Inspeção' WHERE matricula='462';
UPDATE public.employees SET coordenador='Marcos', gerente='Jamerson', processo='Construção' WHERE matricula='16939';
UPDATE public.employees SET coordenador='Julio C.', gerente='Cesar', processo='Inspeção' WHERE matricula='16138';
UPDATE public.employees SET coordenador='Thiago F.', gerente='Cesar', processo='Construção' WHERE matricula='12849';
UPDATE public.employees SET coordenador='Paulo', gerente='Cesar', processo='Plantão' WHERE matricula='17751';
UPDATE public.employees SET coordenador='Rafaela', gerente='Cesar', processo='Construção' WHERE matricula='12928';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='12513';
UPDATE public.employees SET coordenador='Afonso', gerente='Jamerson', processo='Plantão' WHERE matricula='12745';
UPDATE public.employees SET coordenador='Daniel', gerente='Jamerson', processo='Segurança' WHERE matricula='21925';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Poda' WHERE matricula='12506';
UPDATE public.employees SET coordenador='Valvick', gerente='Jamerson', processo='Administrativo' WHERE matricula='12383';
UPDATE public.employees SET coordenador='Luis C.', gerente='Jamerson', processo='Construção' WHERE matricula='12530';
