-- Limpeza de observações antigas: feita no cliente (localStorage do PWA),
-- não no banco — o dashboard precisa dos dados históricos permanentes.
-- Este arquivo existe apenas para documentar a decisão.
--
-- A retenção de 35 dias é aplicada em:
--   POC_Mobile/src/stores/observacoes.ts → loadItems()
