-- Religa observadores à hierarquia da planilha Equipes - OP e ADM.xlsx
-- (abas Equipes + observadores). pwa_equipes já estava com os 218 prefixos.

UPDATE public.employees e SET
  coordenador = NULLIF(v.coordenador, ''),
  gerente = NULLIF(v.gerente, ''),
  processo = COALESCE(NULLIF(v.processo, ''), e.processo)
FROM (VALUES
('22899','Paulo','Cesar','Plantão'),
('12889','Julio C.','Jamerson','Inspeção'),
('12891','Daniel','Cesar','Segurança'),
('12489','Paulo','Cesar','Plantão'),
('13795','Luis C.','Jamerson','Construção'),
('12582','Afonso','Jamerson','Plantão'),
('23847','Afonso','Jamerson','Plantão'),
('20868','Thiago F.','Cesar','Poda'),
('21141','Rafaela','Cesar','Linha Viva'),
('20548','Jackson','Cesar','Construção'),
('13009','Rafaela','Cesar','Construção'),
('15613','Afonso','Jamerson','Plantão'),
('12913','Rafaela','Cesar','Construção'),
('12884','Thiago F.','Cesar','Construção'),
('13023','Paulo','Cesar','Plantão'),
('12898','Rafaela','Cesar','Construção'),
('19837','Camila','Cesar','Almoxarifado'),
('14983','Thiago F.','Cesar','Construção'),
('24036','Marcos','Jamerson','Construção'),
('18311','Jackson','Cesar','Construção'),
('13035','Thiago F.','Cesar','Poda'),
('12762','Luis C.','Jamerson','Linha Viva'),
('17747','Rafaela','Cesar','Construção'),
('21607','Daniel','Cesar','Segurança'),
('24046','Rafaela','Cesar','Construção'),
('12512','Afonso','Jamerson','Plantão'),
('12558','Julio C.','Jamerson','Inspeção'),
('12650','Marcos','Jamerson','Construção'),
('12471','Luis C.','Jamerson','Poda'),
('24088','Paulo','Cesar','Plantão'),
('13818','Julio C.','Cesar','Inspeção'),
('14587','Marcos','Jamerson','Construção'),
('13516','Luis C.','Jamerson','Construção'),
('13315','Luis C.','Jamerson','Linha Viva'),
('12813','Daniel','Cesar','Segurança'),
('12509','Luis C.','Jamerson','Construção'),
('12892','Rafaela','Cesar','Construção'),
('13748','Thiago F.','Cesar','Linha Viva'),
('12534','Marcos','Jamerson','Construção'),
('16938','Jackson','Cesar','Construção'),
('12570','Luis C.','Jamerson','Poda'),
('23741','Marcos','Jamerson','Poda'),
('12939','Rafaela','Cesar','Construção'),
('12751','Luis C.','Jamerson','Construção'),
('12576','Afonso','Jamerson','Plantão'),
('12998','Paulo','Cesar','Plantão'),
('4745','Luis C.','Jamerson','Construção'),
('17084','Julio C.','Jamerson','Inspeção'),
('17753','Jackson','Cesar','Construção'),
('13947','Julio C.','Jamerson','Inspeção'),
('12792','Luis C.','Jamerson','Poda'),
('12820','Thiago F.','Cesar','Construção'),
('23972','Luis C.','Jamerson','Construção'),
('24793','Daniel','Jamerson','Segurança'),
('13754','Marcos','Jamerson','Poda'),
('12686','Luis C.','Jamerson','Construção'),
('15565','Jackson','Cesar','Construção'),
('12621','Luis C.','Jamerson','Construção'),
('12822','Thiago F.','Cesar','Construção'),
('12572','Rafaela','Cesar','Linha Viva'),
('12749','Luis C.','Jamerson','Construção'),
('17462','Marcos','Jamerson','Construção'),
('13410','Marcos','Jamerson','Construção'),
('13073','Afonso','Jamerson','Ligação Nova'),
('13518','Jackson','Cesar','Construção'),
('12742','Marcos','Jamerson','Construção'),
('12851','Jackson','Cesar','Construção'),
('16331','Daniel','Cesar','Segurança'),
('22025','Julio C.','Jamerson','Inspeção'),
('12746','Julio C.','Jamerson','Inspeção'),
('12800','Afonso','Jamerson','Plantão'),
('13100','Marcos','Jamerson','Construção'),
('12595','Afonso','Jamerson','Plantão'),
('16153','Ruan','Jamerson','Oficina'),
('12938','Jackson','Cesar','Construção'),
('12515','Marcos','Jamerson','Construção'),
('12597','Luis C.','Jamerson','Poda'),
('13099','Marcos','Jamerson','Construção'),
('13077','Marcos','Jamerson','Construção'),
('12955','Rafaela','Cesar','Construção'),
('120','Marcos','Jamerson','Construção'),
('12848','Thiago F.','Cesar','Construção'),
('17463','Rafaela','Cesar','Linha Viva'),
('15455','Marcos','Jamerson','Construção'),
('12981','Rafaela','Cesar','Construção'),
('16079','Jackson','Cesar','Construção'),
('12818','Thiago F.','Cesar','Construção'),
('13080','Marcos','Jamerson','Construção'),
('12672','Luis C.','Jamerson','Construção'),
('17746','Marcos','Jamerson','Construção'),
('21614','Daniel','Cesar','Segurança'),
('21574','Daniel','Jamerson','Segurança'),
('12517','Luis C.','Jamerson','Construção'),
('12467','Marcos','Jamerson','Construção'),
('12516','Luis C.','Jamerson','Equipamentos'),
('12852','Thiago F.','Cesar','Construção'),
('12847','Paulo','Cesar','Plantão'),
('12354','Valvick','Jamerson','Administrativo'),
('12842','Paulo','Cesar','Plantão'),
('12724','Afonso','Jamerson','Plantão'),
('12882','Thiago F.','Cesar','tat'),
('13744','Luis C.','Jamerson','Construção'),
('24109','Rafaela','Cesar','Construção'),
('19677','Rafaela','Cesar','Linha Viva'),
('12719','Rafaela','Cesar','Construção'),
('13021','Rafaela','Cesar','Poda'),
('12844','Paulo','Cesar','Plantão'),
('12483','Luis C.','Jamerson','Construção'),
('12479','Afonso','Jamerson','Plantão'),
('22518','Jackson','Cesar','Construção'),
('13060','Marcos','Jamerson','Construção'),
('14475','Ruan','Jamerson','Oficina'),
('462','Julio C.','Jamerson','Inspeção'),
('16939','Marcos','Jamerson','Construção'),
('16138','Julio C.','Cesar','Inspeção'),
('12849','Thiago F.','Cesar','Construção'),
('17751','Paulo','Cesar','Plantão'),
('12928','Rafaela','Cesar','Construção'),
('12513','Luis C.','Jamerson','Construção'),
('12745','Afonso','Jamerson','Plantão'),
('21925','Daniel','Jamerson','Segurança'),
('12506','Luis C.','Jamerson','Poda'),
('12383','Valvick','Jamerson','Administrativo'),
('12530','Luis C.','Jamerson','Construção')
) AS v(matricula, coordenador, gerente, processo)
WHERE e.matricula = v.matricula;

-- Quem nao estava na aba observadores: desambiguacao por equipe da mesma base/gerencia.
UPDATE public.employees SET coordenador = 'Daniel', gerente = 'Jamerson' WHERE matricula IN ('25173','23742','20270') AND coordenador IS NULL;
UPDATE public.employees SET coordenador = 'Luis C.', gerente = 'Jamerson' WHERE matricula IN ('15559','19873') AND coordenador IS NULL;
UPDATE public.employees SET coordenador = 'Valvick', gerente = 'Valvick' WHERE matricula = '12990' AND coordenador IS NULL;
UPDATE public.employees SET coordenador = 'Rafaela', gerente = 'Cesar' WHERE matricula = '22546' AND coordenador IS NULL;
UPDATE public.employees SET coordenador = 'Jackson', gerente = 'Cesar' WHERE matricula = '13750' AND coordenador IS NULL;

INSERT INTO public.employees (matricula, nome, nome_completo, gerencia, base, funcao, ativo, coordenador, gerente, processo)
VALUES
  ('22025', 'Julio C.', 'Julio', 'GERE', 'BCB', 'Coordenador', true, 'Julio C.', 'Jamerson', 'Inspeção'),
  ('21574', 'Normam', 'Normam', 'SESMT', 'BCB', 'Sesmt', true, 'Daniel', 'Jamerson', 'Segurança'),
  ('19677', 'Rafaela', 'Rafaela', 'GOMAN', 'PDT', 'Coordenador', true, 'Rafaela', 'Cesar', 'Linha Viva')
ON CONFLICT (matricula) DO UPDATE SET
  coordenador = excluded.coordenador,
  gerente = excluded.gerente,
  processo = excluded.processo;
